### PR TITLE
Update 8u162

### PR DESCRIPTION
**Pull request by lehn-etracker**
Cookbook Version v8.152.1 does not work anymore. This update provides Java 8.162.

Now against branch `8` of origin repository.

### CODE REVIEW

**Comment by dhoer** [comment]
Thanks for the PR.  This is now published to supermarket.

BTW, would you like to adopt this cookbook or become a contributor?

**Comment by lehn-etracker** [comment]
I can imagine to become a contributor, but not to adopt the whole thing.

**Comment by dhoer** [comment]
Ok, thanks.  Our company has moved away from Chef, so I won't be on top of updates like I was in the past.  I will add you as a contributor on github.  Do you have an account on Supermarket?

**Comment by lehn-etracker** [comment]
> Do you have an account on Supermarket?
Yes, I do. https://supermarket.chef.io/users/lehn-etracker

**Comment by dhoer** [comment]
I added you as a collaborator on Supermarket as well.  Thanks for your PR!

**Pull request merged**
