### PR TITLE
Fix for issue #5 - adding an option to specify public JRE install location

### PR DESCRIPTION
**Pull request by tevert**

### CODE REVIEW

**Comment by dhoer** [comment]
I'm not sure about the name `public_jre_home` because, unlike Windows, Linux is a true multi-user system. You have the choice of installing the JDK or JRE in /usr/java where its publicly available to any user or in a user's private space where only that user can access it.

Maybe `win_jre_home`, since it is only available for windows or `java_jre_home` where support could be expanded to linux and mac in the future.  Either way, the attribute should be place under Windows Only section.

The robocop and chefspec test must pass and chefspec test must be 100%. Run `bundle update` and `bundle exec rake` to run these tests locally.
 
The serverspec default test should be updated to verify the default jre install location is still ok.

Another test kitchen suite should to be added to verify that java_home and jre home work as expected when overridden.   I can do this one if you are not comfortable do that.

**Comment by dhoer** [comment]
It looks like this jre install feature is only available for windows, so I'm leaning towards `win_jre_home` name.

**Comment by dhoer** [comment]
http://docs.oracle.com/javase/8/docs/technotes/guides/install/windows_jdk_install.html#CHDHHBDD

**Comment by dhoer** [comment]
I will probably look at this this weekend to make the win_jre_home change and get the tests passing. Next week is the critical patch update, and I like to get this change in before that update.

**Comment by dhoer** [comment]
I see that those change are made.  Thanks.  I will merge this this weekend.

**Comment by tevert** [comment]
No problem

**Pull request merged**
